[project]
name = "endo-ai"
version = "0.1.0"
description = "EndoReg Db API Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agl-frame-extractor>=0.2.1",
    "albumentations",
    "asgiref",
    "certifi",
    "channels>=4.2.0",
    "daphne>=4.1.2",
    "django>=5.1.3",
    "endoreg-db",
    "endoreg-db-api",
    # "endoreg-db>=0.5.3",
    "icecream",
    "opencv-python>=4.11.0.86",
    "psycopg[binary]>=3.2.3",
    "pydantic",
    "python-ffmpeg",
    "pytorch-lightning>=2.5.0.post0",
    "pyyaml",
    "scipy",
    "torch",
    "torchaudio",
    "torchvision",
    "whitenoise",
]

[tool.setuptools]
packages = ["endo_ai"]

[tool.uv.sources]
endoreg-db-api = { path = "endoreg_db_api_production" }
endoreg-db = { path = "endoreg_db_production" }
agl-frame-extractor = { path = "agl_frame_extractor" }
endo-ai = { path = "endo_ai" }
