[project]
name = "endo-ai"
version = "0.1.0"
description = "EndoReg Db API Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agl-frame-extractor>=0.2.1",
    "albumentations>=2.0.4",
    "asgiref>=3.8.1",
    "certifi>=2025.1.31",
    "channels>=4.2.0",
    "daphne>=4.1.2",
    "django>=5.1.3",
    "endoreg-db>=0.5.3",
    "icecream>=2.1.4",
    "opencv-python>=4.11.0.86",
    "psycopg[binary]>=3.2.3",
    "pydantic>=2.10.6",
    "python-ffmpeg>=2.0.12",
    "pytorch-lightning>=2.5.0.post0",
    "pyyaml>=6.0.2",
    "scipy>=1.15.1",
    "torch>=2.5.1",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0", # Should be same version as version provided in devenv.nix
    "whitenoise>=6.8.2",
]

[tool.setuptools]
packages = ["endo_ai"]
